In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


### Creating tensors with tf.constant

In [2]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)


tf.Tensor(7, shape=(), dtype=int32)
0


In [3]:
vector = tf.constant([10,10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [4]:
matrix = tf.constant( [[1,2,3],[4,5,3],[2,32,1]] )
matrix2 = tf.constant( [[1,21,3],[41,5,3],[22,32,11]] )

matrix.shape ,matrix2.shape


(TensorShape([3, 3]), TensorShape([3, 3]))

In [5]:
print(matrix@matrix2)

print()
print(tf.matmul(matrix ,matrix2))

tf.Tensor(
[[ 149  127   42]
 [ 275  205   60]
 [1336  234  113]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[ 149  127   42]
 [ 275  205   60]
 [1336  234  113]], shape=(3, 3), dtype=int32)


In [6]:
vector=tf.constant([-1.0,2.0])

print(vector.dtype,"\n")

b= tf.cast(vector ,tf.float16)
print(b.dtype)

<dtype: 'float32'> 

<dtype: 'float16'>


In [7]:
print(tf.abs(vector),"\n")
# print(vector)

tf.Tensor([1. 2.], shape=(2,), dtype=float32) 



In [8]:
import numpy as np


In [9]:
arr= np.random.randint(0,100,23)
print(arr)

print("\n")
ten = tf.constant(arr)
print(ten)
print("\n")



[56  8 62  7 63 16 99 29  2 39 79 85  1 25 82 52 51 36 39 54 41 59 80]


tf.Tensor([56  8 62  7 63 16 99 29  2 39 79 85  1 25 82 52 51 36 39 54 41 59 80], shape=(23,), dtype=int64)




In [10]:
# For std we need to convert our values from int to float
print(tf.math.reduce_std( tf.cast(ten ,dtype=tf.float32) ))


tf.Tensor(27.652243, shape=(), dtype=float32)


In [11]:
#squeezing a tensor(removing all single dimensions)

# Create a tensor to get started
import numpy as np
np.random.seed(42)
G = np.random.uniform(size=50)
ten = tf.constant(G)
ten2=tf.reshape(ten,shape=(1,1,1,50) )
ten2

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float64, numpy=
array([[[[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
          0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
          0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
          0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
          0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
          0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041,
          0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
          0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249,
          0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
          0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446]]]])>

In [12]:
G_squeezed= tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
       0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
       0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041,
       0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
       0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249,
       0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
       0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446])>

In [13]:
# One Hot encoding
some_list =[0,8,2,3] #red ,green ,blue ,purple
depth=6

tf.one_hot(some_list ,4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [14]:
a=tf.constant([3.,4.])
print(a.numpy()[0])

# Default time of both are slightly differnet
numpy_j = tf.constant(np.array(np.array([3.,7.,10.])))

tensor_j=tf.constant([3.,7.,10.])
numpy_j=tf.cast(numpy_j ,dtype=tf.float32)
numpy_j.dtype , tensor_j.dtype

3.0


(tf.float32, tf.float32)

In [15]:
print(tf.config)

<module 'tensorflow._api.v2.config' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/config/__init__.py'>


In [18]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [19]:
!nvidia-smi

Mon Dec  9 17:27:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0              30W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--